package Others;

import Entity.Transaction;

/**
 *
 * @author Angel Ponce
 */
public class JTransaction extends javax.swing.JPanel {

    private Transaction transaction;

    /**
     * Creates new form JTransaction
     */
    public JTransaction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amount = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        date = new javax.swing.JLabel();

        amount.setText("jLabel1");

        type.setText("jLabel2");

        date.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(amount)
                .addGap(67, 67, 67)
                .addComponent(type)
                .addGap(67, 67, 67)
                .addComponent(date)
                .addGap(0, 91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount)
                    .addComponent(type)
                    .addComponent(date))
                .addContainerGap(241, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel amount;
    public javax.swing.JLabel date;
    public javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
