package View;

import Others.Helper;
import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;
import java.awt.Color;
import javax.swing.UIManager;
import jiconfont.icons.google_material_design_icons.GoogleMaterialDesignIcons;

/**
 *
 * @author samyc
 */
public class ATMView extends javax.swing.JFrame {

    /**
     * Creates new form ATMView
     */
    public ATMView() {
        defaultTheme();
        initComponents();
        pick.putClientProperty("JButton.buttonType", "roundRect");
        addUser.setIcon(Helper.icon(GoogleMaterialDesignIcons.ADD_CIRCLE, 32, new Color(10, 61, 98)));
        initATM.setIcon(Helper.icon(GoogleMaterialDesignIcons.PLAY_CIRCLE_FILLED, 32, new Color(10, 61, 98)));
        addCash.setIcon(Helper.icon(GoogleMaterialDesignIcons.ADD_CIRCLE, 32, new Color(10, 61, 98)));
        updateCard.setIcon(Helper.icon(GoogleMaterialDesignIcons.PAYMENT, 32, new Color(10, 61, 98)));
        updateLimit.setIcon(Helper.icon(GoogleMaterialDesignIcons.MONEY_OFF, 32, new Color(10, 61, 98)));
        userConsult.setIcon(Helper.icon(GoogleMaterialDesignIcons.PERSON, 32, new Color(10, 61, 98)));
        userControl.setIcon(Helper.icon(GoogleMaterialDesignIcons.PEOPLE, 32, new Color(10, 61, 98)));
        updatePin.setIcon(Helper.icon(GoogleMaterialDesignIcons.LOCK_OPEN, 32, new Color(10, 61, 98)));
        retreat.setIcon(Helper.icon(GoogleMaterialDesignIcons.PAYMENT, 32, new Color(10, 61, 98)));
        deposit.setIcon(Helper.icon(GoogleMaterialDesignIcons.MONETIZATION_ON, 32, new Color(10, 61, 98)));
        transactions.setIcon(Helper.icon(GoogleMaterialDesignIcons.HISTORY, 32, new Color(10, 61, 98)));
        amount.setIcon(Helper.icon(GoogleMaterialDesignIcons.MONETIZATION_ON, 32, new Color(10, 61, 98)));
        super.setLocationRelativeTo(null);
    }
    
    public void defaultTheme() {
        FlatArcDarkIJTheme.setup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        container = new javax.swing.JPanel();
        barNavigation = new javax.swing.JPanel();
        pick = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        addUser = new javax.swing.JButton();
        initATM = new javax.swing.JButton();
        addCash = new javax.swing.JButton();
        updateCard = new javax.swing.JButton();
        updateLimit = new javax.swing.JButton();
        userConsult = new javax.swing.JButton();
        userControl = new javax.swing.JButton();
        updatePin = new javax.swing.JButton();
        retreat = new javax.swing.JButton();
        deposit = new javax.swing.JButton();
        transactions = new javax.swing.JButton();
        amount = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 752));
        setPreferredSize(new java.awt.Dimension(1080, 752));

        container.setMinimumSize(new java.awt.Dimension(1080, 752));
        container.setLayout(new java.awt.GridBagLayout());

        barNavigation.setBackground(new java.awt.Color(64, 64, 122));
        barNavigation.setLayout(new java.awt.GridBagLayout());

        pick.setMaximumSize(new java.awt.Dimension(192, 192));
        pick.setMinimumSize(new java.awt.Dimension(192, 192));
        pick.setPreferredSize(new java.awt.Dimension(192, 192));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 100.0;
        barNavigation.add(pick, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Name Lastname");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 100.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        barNavigation.add(jLabel1, gridBagConstraints);

        addUser.setBackground(new java.awt.Color(99, 167, 212));
        addUser.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        addUser.setForeground(new java.awt.Color(255, 255, 255));
        addUser.setText("Add user");
        addUser.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 100.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        barNavigation.add(addUser, gridBagConstraints);

        initATM.setBackground(new java.awt.Color(99, 167, 212));
        initATM.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        initATM.setForeground(new java.awt.Color(255, 255, 255));
        initATM.setText("Init ATM");
        initATM.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 100.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        barNavigation.add(initATM, gridBagConstraints);

        addCash.setBackground(new java.awt.Color(99, 167, 212));
        addCash.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        addCash.setForeground(new java.awt.Color(255, 255, 255));
        addCash.setText("Add cash");
        addCash.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 100.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        barNavigation.add(addCash, gridBagConstraints);

        updateCard.setBackground(new java.awt.Color(99, 167, 212));
        updateCard.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        updateCard.setForeground(new java.awt.Color(255, 255, 255));
        updateCard.setText("Update card");
        updateCard.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 100.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        barNavigation.add(updateCard, gridBagConstraints);

        updateLimit.setBackground(new java.awt.Color(99, 167, 212));
        updateLimit.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        updateLimit.setForeground(new java.awt.Color(255, 255, 255));
        updateLimit.setText("Update limit");
        updateLimit.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 100.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        barNavigation.add(updateLimit, gridBagConstraints);

        userConsult.setBackground(new java.awt.Color(99, 167, 212));
        userConsult.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        userConsult.setForeground(new java.awt.Color(255, 255, 255));
        userConsult.setText("User consult");
        userConsult.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 100.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        barNavigation.add(userConsult, gridBagConstraints);

        userControl.setBackground(new java.awt.Color(99, 167, 212));
        userControl.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        userControl.setForeground(new java.awt.Color(255, 255, 255));
        userControl.setText("User control");
        userControl.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 100.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        barNavigation.add(userControl, gridBagConstraints);

        updatePin.setBackground(new java.awt.Color(99, 167, 212));
        updatePin.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        updatePin.setForeground(new java.awt.Color(255, 255, 255));
        updatePin.setText("Update pin");
        updatePin.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 100.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        barNavigation.add(updatePin, gridBagConstraints);

        retreat.setBackground(new java.awt.Color(99, 167, 212));
        retreat.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        retreat.setForeground(new java.awt.Color(255, 255, 255));
        retreat.setText("Retreat");
        retreat.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 100.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        barNavigation.add(retreat, gridBagConstraints);

        deposit.setBackground(new java.awt.Color(99, 167, 212));
        deposit.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        deposit.setForeground(new java.awt.Color(255, 255, 255));
        deposit.setText("Deposit");
        deposit.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 100.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        barNavigation.add(deposit, gridBagConstraints);

        transactions.setBackground(new java.awt.Color(99, 167, 212));
        transactions.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        transactions.setForeground(new java.awt.Color(255, 255, 255));
        transactions.setText("Transactions");
        transactions.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 100.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        barNavigation.add(transactions, gridBagConstraints);

        amount.setBackground(new java.awt.Color(99, 167, 212));
        amount.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        amount.setForeground(new java.awt.Color(255, 255, 255));
        amount.setText("Amount");
        amount.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 100.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        barNavigation.add(amount, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 15.0;
        gridBagConstraints.weighty = 100.0;
        container.add(barNavigation, gridBagConstraints);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 85.0;
        gridBagConstraints.weighty = 100.0;
        container.add(content, gridBagConstraints);

        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATMView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATMView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATMView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATMView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATMView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCash;
    private javax.swing.JButton addUser;
    private javax.swing.JButton amount;
    private javax.swing.JPanel barNavigation;
    private javax.swing.JPanel container;
    private javax.swing.JPanel content;
    private javax.swing.JButton deposit;
    private javax.swing.JButton initATM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pick;
    private javax.swing.JButton retreat;
    private javax.swing.JButton transactions;
    private javax.swing.JButton updateCard;
    private javax.swing.JButton updateLimit;
    private javax.swing.JButton updatePin;
    private javax.swing.JButton userConsult;
    private javax.swing.JButton userControl;
    // End of variables declaration//GEN-END:variables
}
