/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Others.Helper;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;
import java.awt.Color;
import javax.swing.UIManager;
import jiconfont.icons.google_material_design_icons.GoogleMaterialDesignIcons;

/**
 *
 * @author samyc
 */
public class CreateUserView extends javax.swing.JPanel {

    /**
     * Creates new form CreateUserView
     */
    public CreateUserView() {
        defaultTheme();
        initComponents();
        name.putClientProperty("JTextField.placeholderText", "Name");
        lastName.putClientProperty("JTextField.placeholderText", "Lastname");
        email.putClientProperty("JTextField.placeholderText", "Email");
        age.putClientProperty("JTextField.placeholderText", "Age");
        numberCard.putClientProperty("JTextField.placeholderText", "Number Card");
        pin.putClientProperty("JTextField.placeholderText", "Pin");
        initialAmount.putClientProperty("JTextField.placeholderText", "Initial Amount");
        maximumAmount.putClientProperty("JTextField.placeholderText", "Maximum Amount");
        save.setIcon(Helper.icon(GoogleMaterialDesignIcons.SAVE, 32, Color.decode("#0A3D62")));
        choosePick.setIcon(Helper.icon(GoogleMaterialDesignIcons.IMAGE, 32, Color.LIGHT_GRAY));
    }
  public void defaultTheme() {
        FlatArcDarkIJTheme.setup();
        UIManager.put("Button.arc", 999);
        UIManager.put("Component.arc", 999);
        UIManager.put("ProgressBar.arc", 999);
        UIManager.put("TextComponent.arc", 999);
        FlatLaf.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fileChooser = new javax.swing.JFileChooser();
        header = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        age = new javax.swing.JSpinner();
        numberCard = new javax.swing.JFormattedTextField();
        initialAmount = new javax.swing.JFormattedTextField();
        pin = new javax.swing.JFormattedTextField();
        maximumAmount = new javax.swing.JFormattedTextField();
        footer = new javax.swing.JPanel();
        pick = new javax.swing.JButton();
        choosePick = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(918, 800));
        setLayout(new java.awt.BorderLayout());

        header.setLayout(new java.awt.GridBagLayout());

        title.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        title.setText("Add User");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        header.add(title, gridBagConstraints);

        save.setBackground(new java.awt.Color(68, 189, 50));
        save.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Save");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        header.add(save, gridBagConstraints);

        add(header, java.awt.BorderLayout.NORTH);

        container.setLayout(new java.awt.GridBagLayout());

        name.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        name.setPreferredSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        container.add(name, gridBagConstraints);

        lastName.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lastName.setPreferredSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        container.add(lastName, gridBagConstraints);

        email.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        email.setPreferredSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        container.add(email, gridBagConstraints);

        age.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        age.setToolTipText("Age");
        age.setPreferredSize(new java.awt.Dimension(37, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        container.add(age, gridBagConstraints);

        numberCard.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        numberCard.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        numberCard.setPreferredSize(new java.awt.Dimension(4, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        container.add(numberCard, gridBagConstraints);

        initialAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        initialAmount.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        initialAmount.setPreferredSize(new java.awt.Dimension(4, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        container.add(initialAmount, gridBagConstraints);

        pin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        pin.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        pin.setPreferredSize(new java.awt.Dimension(4, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        container.add(pin, gridBagConstraints);

        maximumAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        maximumAmount.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        maximumAmount.setPreferredSize(new java.awt.Dimension(4, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        container.add(maximumAmount, gridBagConstraints);

        add(container, java.awt.BorderLayout.CENTER);

        footer.setLayout(new javax.swing.BoxLayout(footer, javax.swing.BoxLayout.X_AXIS));

        pick.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        pick.setBorderPainted(false);
        pick.setMaximumSize(new java.awt.Dimension(256, 256));
        pick.setMinimumSize(new java.awt.Dimension(256, 256));
        pick.setPreferredSize(new java.awt.Dimension(256, 256));
        footer.add(pick);

        choosePick.setBackground(new java.awt.Color(10, 61, 98));
        choosePick.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        choosePick.setText("Choose a pick");
        choosePick.setMargin(new java.awt.Insets(0, 0, 0, 0));
        choosePick.setMinimumSize(new java.awt.Dimension(256, 40));
        choosePick.setPreferredSize(new java.awt.Dimension(256, 40));
        footer.add(choosePick);

        add(footer, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JSpinner age;
    public javax.swing.JButton choosePick;
    public javax.swing.JPanel container;
    public javax.swing.JTextField email;
    public javax.swing.JFileChooser fileChooser;
    public javax.swing.JPanel footer;
    public javax.swing.JPanel header;
    public javax.swing.JFormattedTextField initialAmount;
    public javax.swing.JTextField lastName;
    public javax.swing.JFormattedTextField maximumAmount;
    public javax.swing.JTextField name;
    public javax.swing.JFormattedTextField numberCard;
    public javax.swing.JButton pick;
    public javax.swing.JFormattedTextField pin;
    public javax.swing.JButton save;
    public javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
