package View;

import Controller.UserController;
import Entity.Person;
import Entity.Transaction;

/**
 *
 * @author Angel Ponce
 */
public class JTransaction extends javax.swing.JPanel {

    private Transaction transaction;

    /**
     * Creates new form JTransaction
     *
     * @param transaction
     */
    public JTransaction(Transaction transaction) {
        this.transaction = transaction;
        initComponents();
        this.amount.setText(UserController.USD.format(transaction.getAmount()));
        this.type.setText(transaction.getType());
        this.date.setText(Person.dateFormat.format(transaction.getDate()));
    }

    public JTransaction(String amount, String type, String date) {
        initComponents();
        this.amount.setText(amount);
        this.type.setText(type);
        this.date.setText(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amount = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        date = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 50));
        setMinimumSize(new java.awt.Dimension(123, 50));
        setPreferredSize(new java.awt.Dimension(400, 50));
        setLayout(new java.awt.GridLayout());

        amount.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        amount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(amount);

        type.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        type.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(type);

        date.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(date);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel amount;
    public javax.swing.JLabel date;
    public javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
