/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Others.Helper;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;
import javax.swing.UIManager;

/**
 *
 * @author samyc
 */
public class UserConsultView extends javax.swing.JPanel {

    /**
     * Creates new form UserConsultView
     */
    public UserConsultView() {
        defaultTheme();
        initComponents();
        maxRetreat.setIcon(Helper.roundImage(getClass().getResource("/Resources/c1.png"), 192, 192));
        retreats.setIcon(Helper.roundImage(getClass().getResource("/Resources/c2.png"), 192, 192));
        actualAmount.setIcon(Helper.roundImage(getClass().getResource("/Resources/c3.png"), 192, 192));
        lastAccess.setIcon(Helper.roundImage(getClass().getResource("/Resources/c4.png"), 192, 192));
    }

    public void defaultTheme() {
        FlatArcDarkIJTheme.setup();
        UIManager.put("Button.arc", 999);
        UIManager.put("Component.arc", 999);
        UIManager.put("ProgressBar.arc", 999);
        UIManager.put("TextComponent.arc", 999);
        FlatLaf.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        scroll = new javax.swing.JScrollPane();
        users = new javax.swing.JPanel();
        information = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        maxRetreat = new javax.swing.JButton();
        maxRetreatLabel = new javax.swing.JLabel();
        panel4 = new javax.swing.JPanel();
        lastAccess = new javax.swing.JButton();
        lastAccessLabel = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        actualAmount = new javax.swing.JButton();
        actualAmountLabel = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        retreats = new javax.swing.JButton();
        retreatsLabel = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        load = new javax.swing.JProgressBar();

        setLayout(new java.awt.GridBagLayout());

        scroll.setMinimumSize(new java.awt.Dimension(250, 20));
        scroll.setPreferredSize(new java.awt.Dimension(250, 3));

        users.setLayout(new javax.swing.BoxLayout(users, javax.swing.BoxLayout.Y_AXIS));
        scroll.setViewportView(users);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 40.0;
        gridBagConstraints.weighty = 100.0;
        add(scroll, gridBagConstraints);

        information.setLayout(new java.awt.GridBagLayout());

        panel1.setLayout(new java.awt.GridBagLayout());

        maxRetreat.setFont(new java.awt.Font("Montserrat", 1, 30)); // NOI18N
        maxRetreat.setForeground(new java.awt.Color(255, 255, 255));
        maxRetreat.setBorderPainted(false);
        maxRetreat.setFocusable(false);
        maxRetreat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        maxRetreat.setPreferredSize(new java.awt.Dimension(192, 192));
        panel1.add(maxRetreat, new java.awt.GridBagConstraints());

        maxRetreatLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        maxRetreatLabel.setText("Max Retreat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panel1.add(maxRetreatLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        information.add(panel1, gridBagConstraints);

        panel4.setLayout(new java.awt.GridBagLayout());

        lastAccess.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        lastAccess.setForeground(new java.awt.Color(255, 255, 255));
        lastAccess.setBorderPainted(false);
        lastAccess.setFocusable(false);
        lastAccess.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lastAccess.setPreferredSize(new java.awt.Dimension(192, 192));
        panel4.add(lastAccess, new java.awt.GridBagConstraints());

        lastAccessLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lastAccessLabel.setText("Last Access");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panel4.add(lastAccessLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        information.add(panel4, gridBagConstraints);

        panel3.setLayout(new java.awt.GridBagLayout());

        actualAmount.setFont(new java.awt.Font("Montserrat", 1, 30)); // NOI18N
        actualAmount.setForeground(new java.awt.Color(255, 255, 255));
        actualAmount.setBorderPainted(false);
        actualAmount.setFocusable(false);
        actualAmount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        actualAmount.setPreferredSize(new java.awt.Dimension(192, 192));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panel3.add(actualAmount, gridBagConstraints);

        actualAmountLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        actualAmountLabel.setText("Actual Amount");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panel3.add(actualAmountLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        information.add(panel3, gridBagConstraints);

        panel2.setLayout(new java.awt.GridBagLayout());

        retreats.setFont(new java.awt.Font("Montserrat", 1, 30)); // NOI18N
        retreats.setForeground(new java.awt.Color(255, 255, 255));
        retreats.setBorderPainted(false);
        retreats.setFocusable(false);
        retreats.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        retreats.setPreferredSize(new java.awt.Dimension(192, 192));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panel2.add(retreats, gridBagConstraints);

        retreatsLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        retreatsLabel.setText("Retreats");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panel2.add(retreatsLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        information.add(panel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 60.0;
        gridBagConstraints.weighty = 100.0;
        add(information, gridBagConstraints);

        header.setLayout(new java.awt.GridBagLayout());

        title.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        title.setText("Users");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 100.0;
        header.add(title, gridBagConstraints);

        load.setFont(new java.awt.Font("Montserrat", 2, 18)); // NOI18N
        load.setPreferredSize(new java.awt.Dimension(146, 30));
        load.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 100.0;
        header.add(load, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 100.0;
        add(header, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton actualAmount;
    public javax.swing.JLabel actualAmountLabel;
    public javax.swing.JPanel header;
    public javax.swing.JPanel information;
    public javax.swing.JButton lastAccess;
    public javax.swing.JLabel lastAccessLabel;
    public javax.swing.JProgressBar load;
    public javax.swing.JButton maxRetreat;
    public javax.swing.JLabel maxRetreatLabel;
    public javax.swing.JPanel panel1;
    public javax.swing.JPanel panel2;
    public javax.swing.JPanel panel3;
    public javax.swing.JPanel panel4;
    public javax.swing.JButton retreats;
    public javax.swing.JLabel retreatsLabel;
    public javax.swing.JScrollPane scroll;
    public javax.swing.JLabel title;
    public javax.swing.JPanel users;
    // End of variables declaration//GEN-END:variables
}
